# Change these first
owner: Ilger-Supporto # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: Ilger
    url: $ILG_COM

  - name: MTA1
    check: "tcp-ping"
    url: $MTA1
    port: 25

  - name: MTA2
    check: "tcp-ping"
    url: $MTA2
    port: 25

  - name: MTA3
    check: "tcp-ping"
    url: $MTA3
    port: 25
  
  - name: MTA4
    check: "tcp-ping"
    url: $MTA4
    port: 25
    
  - name: MTA5
    check: "tcp-ping"
    url: $MTA5
    port: 25
  
  - name: MTA6
    check: "tcp-ping"
    url: $MTA6
    port: 25
    
  - name: MTA7
    check: "tcp-ping"
    url: $MTA7
    port: 25
  
  - name: MTA8
    check: "tcp-ping"
    url: $MTA8
    port: 25

  - name: PRX1
    url: $PRX1

  - name: PRX2
    url: $PRX2

  - name: PRX3
    url: $PRX3

  - name: PRX4
    url: $PRX4

  - name: NEWS02_BIBLIO
    url: $NEWS02_BIBLIO

  - name: MX8
    check: "tcp-ping"
    url: $MX8
    port: 25
  
  - name: MX9
    check: "tcp-ping"
    url: $MX9
    port: 25
          
  - name: MX10
    check: "tcp-ping"
    url: $MX10
    port: 25
  
  - name: MX11
    check: "tcp-ping"
    url: $MX11
    port: 25
    
  - name: MX12
    check: "tcp-ping"
    url: $MX12
    port: 25
  
  - name: PRX_Z_1
    url: $PRX_Z_1

  - name: PRX_Z_2
    url: $PRX_Z_2

  - name: PRX_Z_3
    url: $PRX_Z_3

  - name: PRX_Z_4
    url: $PRX_Z_4

  - name: MTA2-DC
    check: "tcp-ping"
    url: $MTA2_DC
    port: 25

  - name: MTA3-DC
    check: "tcp-ping"
    url: $MTA3_DC
    port: 25

  - name: MTA4-DC
    check: "tcp-ping"
    url: $MTA4_DC
    port: 25

  - name: KOS02
    check: "tcp-ping"
    url: $KOS02
    port: 25

  - name: EMAILIT02
    check: "tcp-ping"
    url: $EMAILIT02
    port: 25

  - name: SMTP3_QWEB
    check: "tcp-ping"
    url: $SMTP3_QWEB
    port: 25

  - name: SMTP2_ILGER
    check: "tcp-ping"
    url: $SMTP2_ILGER
    port: 25

  - name: SMTP3_ILGER
    check: "tcp-ping"
    url: $SMTP3_ILGER
    port: 25

  - name: SMTP4_ILGER
    check: "tcp-ping"
    url: $SMTP4_ILGER
    port: 25

  - name: SMTP5_ILGER
    check: "tcp-ping"
    url: $SMTP5_ILGER
    port: 25

  - name: SMTP6_ILGER
    check: "tcp-ping"
    url: $SMTP6_ILGER
    port: 25

  - name: SMTPMEDICASA
    check: "tcp-ping"
    url: $SMTPMEDICASA
    port: 25

  - name: SMTP7_ILGER
    check: "tcp-ping"
    url: $SMTP7_ILGER
    port: 25

  - name: SMTP8_ILGER
    check: "tcp-ping"
    url: $SMTP8_ILGER
    port: 25

  - name: SMTP9_ILGER
    check: "tcp-ping"
    url: $SMTP9_ILGER
    port: 25

  - name: SMTP10_ILGER
    check: "tcp-ping"
    url: $SMTP10_ILGER
    port: 25

  - name: SMTP11_ILGER
    check: "tcp-ping"
    url: $SMTP11_ILGER
    port: 25

  - name: PRX_2_DC
    url: $PRX_2_DC

  - name: PRX_3_DC
    url: $PRX_3_DC

  - name: MX3
    url: $MX3

  - name: MX2
    url: $MX2

  - name: OPEN12
    url: $OPEN12

  - name: Z_POLARIS
    url: $Z_POLARIS

  - name: POSTA_ZEUS
    url: $POSTA_ZEUS

  - name: SPIDER4WEB
    url: $SPIDER4WEB

  - name: BBMNET
    url: $BBMNET

  - name: Z02_CASACURA
    url: $Z02_CASACURA

    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  name: ilger
  logoUrl: https://www.ilger.com/wp-content/uploads/2021/11/ILGER-logo.png
  baseUrl: /Uptime
  icon: https://www.ilger.com/wp-content/uploads/2022/03/ilger-logo-favicon.png
  introTitle: "Servers Uptime"
  introMessage: Status page with **real-time** data
  navbar:
    - title: Status
      href: /Uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
